// AUTO-GENERATED by scripts/generate-items-index.mjs — do not edit by hand.
// Add a new item by dropping a file in this folder that exports
// `export const YOUR_NAME: ItemOfDay = {...}` — it's picked up automatically
// the next time the dev server starts, and live while `npm run dev` is
// already running.
import type { ItemOfDay } from "../../types/item";
import { COMPACT_DISC } from "./compactDisc";
import { FLUORIDE_TOOTHPASTE } from "./fluorideToothpaste";
import { OLYMPIC_GOLD_MEDAL } from "./goldMedal";
import { LITHIUM_ION_BATTERY } from "./lithiumIonBattery";
import { MATCHSTICK_TIP } from "./matchstickTip";

export const ITEMS: ItemOfDay[] = [
  COMPACT_DISC,
  FLUORIDE_TOOTHPASTE,
  OLYMPIC_GOLD_MEDAL,
  LITHIUM_ION_BATTERY,
  MATCHSTICK_TIP,
];

export function itemById(id: string): ItemOfDay {
  const found = ITEMS.find((item) => item.id === id);
  return found ?? ITEMS[0];
}
